name: spotfiy_rec
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  spotify: ^0.12.0
  shared_preferences: ^2.3.3
  http: ^1.1.0
  flutter_secure_storage: ^9.2.2
  flutter_web_auth: ^0.5.0
  intl: ^0.20.1
  fl_chart: ^0.70.1
  card_swiper: ^3.0.1
  lottie: ^3.0.0
  just_audio: ^0.9.46
  spotify_sdk: ^2.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons:

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "images/logo.png"
    
flutter:
  uses-material-design: true
  assets:
    - images/logo.png








